services:
  postgres:
    image: postgres:16
    container_name: crf_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 20

  db_init:
    image: postgres:16
    container_name: crf_db_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./scripts/init_db.sql:/init_db.sql:ro
    command: >
      bash -lc "set -e
      psql -h postgres -U $$POSTGRES_USER -d $$POSTGRES_DB -v ON_ERROR_STOP=1 -c \"CREATE SCHEMA IF NOT EXISTS mlflow;\" &&
      psql -h postgres -U $$POSTGRES_USER -d $$POSTGRES_DB -v ON_ERROR_STOP=1 -f /init_db.sql"
    restart: "no"

  mlflow:
    image: python:3.11-slim
    container_name: crf_mlflow
    depends_on:
      db_init:
        condition: service_completed_successfully
    environment:
      MLFLOW_TRACKING_URI: http://0.0.0.0:5000
      BACKEND_STORE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?options=-csearch_path%3Dmlflow
      ARTIFACT_ROOT: /mlruns
    volumes:
      - ./mlruns:/mlruns
    ports:
      - "${MLFLOW_HOST_PORT:-5001}:5000"
    command: >
      bash -lc "pip install --no-cache-dir mlflow psycopg2-binary &&
      mlflow server --host 0.0.0.0 --port 5000
      --backend-store-uri $$BACKEND_STORE_URI
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination $$ARTIFACT_ROOT
      --allowed-hosts 'mlflow:5000,mlflow,localhost:*,127.0.0.1:*'"

  pipeline:
    build: .
    container_name: crf_pipeline
    user: "50000:0"
    depends_on:
      mlflow:
        condition: service_started
      db_init:
        condition: service_completed_successfully
    environment:
      LC_RAW_PATH: ${LC_RAW_PATH}
      OUTPUT_DIR: ${OUTPUT_DIR}
      DB_DSN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME}
    volumes:
      - ./data:/opt/project/data
      - ./mlruns:/opt/project/mlruns
      - ./mlruns:/mlruns
      - ./src:/opt/project/src
    command: ["bash", "/opt/project/scripts/entrypoint.sh"]

  airflow:
    image: apache/airflow:2.9.3-python3.11
    container_name: crf_airflow
    depends_on:
      mlflow:
        condition: service_started
      db_init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__LOGGING__LOG_CLI_ACTIONS: "false"

      # прокидываем те же env для шагов
      LC_RAW_PATH: /opt/airflow/data/raw/accepted_loans.csv
      OUTPUT_DIR: /opt/airflow/data/processed
      DB_DSN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_EXPERIMENT_NAME: ${MLFLOW_EXPERIMENT_NAME}
      MLFLOW_ARTIFACT_URI: file:/opt/airflow/mlruns

      AIRFLOW_USERNAME: ${AIRFLOW_USERNAME}
      AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD}
      AIRFLOW_EMAIL: ${AIRFLOW_EMAIL}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./src:/opt/airflow/src
      - ./scripts:/opt/airflow/scripts
      - ./requirements.txt:/opt/airflow/requirements.txt:ro
      - ./mlruns:/opt/airflow/mlruns
      - ./mlruns:/mlruns
    ports:
      - "8080:8080"
    command: >
      bash -lc "
      airflow db migrate &&
      airflow connections create-default-connections &&
      airflow users create --username $$AIRFLOW_USERNAME --password $$AIRFLOW_PASSWORD --firstname Admin --lastname User --role Admin --email $$AIRFLOW_EMAIL || true &&
      airflow scheduler & exec airflow webserver
      "

volumes:
  pgdata:
